In [2]:
from easyeda import eda
import pandas as pd
from sklearn import datasets
from sklearn.model_selection import train_test_split

In [3]:
boston = datasets.load_boston()
df = pd.DataFrame(boston.data,columns=boston.feature_names)
df['label'] = boston.target
dftrain,dftest = train_test_split(df,test_size=0.3)
dfeda = eda(dftrain,dftest,language='Chinese')

start exploration data analysis...

================================================================================ 2019-11-21 12:42:34
step1: count features & samples...

train samples number : 354
test samples number : 152
features number : 13


================================================================================ 2019-11-21 12:42:34
step2: evaluate not nan ratio...



================================================================================ 2019-11-21 12:42:34
step3: evaluate not zero ratio...



================================================================================ 2019-11-21 12:42:34
step4: evaluate not negative ratio...



================================================================================ 2019-11-21 12:42:34
step5: evaluate classes count...

progress: 100%|███████████████████████████████████████████████████████████████████████| 14/14 [00:00<00:00, 778.88it/s]

================================================================================ 2019-11-21 12:42:34
step6: evaluate most value...



================================================================================ 2019-11-21 12:42:34
step7: evaluate relativity...

progress: 100%|███████████████████████████████████████████████████████████████████████| 14/14 [00:00<00:00, 501.33it/s]

================================================================================ 2019-11-21 12:42:34
step8: evaluate stability...

progress: 100%|███████████████████████████████████████████████████████████████████████| 14/14 [00:00<00:00, 275.14it/s]

================================================================================ 2019-11-21 12:42:34
step9: evaluate value distribution...

progress: 100%|██████████████████████████████████████████████████████████████████████| 14/14 [00:00<00:00, 7018.08it/s]

================================================================================ 2019-11-21 12:42:34
tast end...

In [4]:
dfeda

         非空率     非空非零率  非空非零非负1率  ...       相关性      同分布性                                               取值分布
CRIM     1.0  1.000000  1.000000  ...  0.408580  0.930196  [(14.3337, 2), (0.1396, 1), (0.02985, 1), (0.3...
ZN       1.0  0.257062  0.257062  ...  0.336057  0.964503  [(0.0, 263), (20.0, 12), (80.0, 11), (22.0, 9)...
INDUS    1.0  1.000000  1.000000  ...  0.507533  0.948298  [(18.1, 93), (19.58, 17), (6.2, 15), (21.89, 1...
CHAS     1.0  0.062147  0.062147  ...  0.057201  0.976621                            [(0.0, 332), (1.0, 22)]
NOX      1.0  1.000000  1.000000  ...  0.564288  0.936069  [(0.437, 14), (0.624, 13), (0.693, 13), (0.538...
RM       1.0  1.000000  1.000000  ...  0.525919  0.932464  [(6.405, 3), (6.167, 2), (6.951, 2), (6.431, 2...
AGE      1.0  1.000000  1.000000  ...  0.497766  0.910162  [(100.0, 31), (96.0, 4), (95.4, 4), (87.9, 3),...
DIS      1.0  1.000000  1.000000  ...  0.452630  0.921424  [(3.4952, 4), (6.0622, 3), (3.9454, 3), (5.287...
RAD      1.0  1.000000  1.000000  ...  0.341675  0.958928  [(24.0, 93), (4.0, 81), (5.0, 77), (3.0, 22), ...
TAX      1.0  1.000000  1.000000  ...  0.464568  0.960117  [(666.0, 93), (307.0, 26), (403.0, 17), (437.0...
PTRATIO  1.0  1.000000  1.000000  ...  0.537858  0.919417  [(20.2, 101), (14.7, 19), (17.4, 15), (21.0, 1...
B        1.0  1.000000  1.000000  ...  0.269280  0.928635  [(396.9, 84), (393.74, 3), (395.24, 3), (394.1...
LSTAT    1.0  1.000000  1.000000  ...  0.695161  0.934136  [(6.36, 3), (8.05, 3), (7.44, 2), (17.6, 2), (...
label    1.0  1.000000  1.000000  ...  1.000000  0.952498  [(50.0, 11), (23.1, 7), (25.0, 6), (20.6, 6), ...

[14 rows x 8 columns]